apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://animeon.ru:9090
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
  - name: infinity
    type: "yesoreyeram-infinity-datasource"
    url: "https://animeon.ru/api/dashboard"
    basicAuth: false
    basicAuthUser: ""
    isDefault: false
    jsonData:
      global_queries: []
      pdcInjected: false
      tlsAuth: false
      tlsSkipVerify: true
    readOnly: false
    apiVersion: ""
